// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4097.DeepSpace.subsystems;


import org.usfirst.frc4097.DeepSpace.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class SpaceVaccuum extends Subsystem {
    double start = 45;
    double end = 150;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private VictorSP propeller;
    private Servo servo1;
    private Servo servo2;
    private Servo servo3;
    private Servo servo4;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    boolean suckStatus = true;
    boolean fanstatus = false;
    public SpaceVaccuum() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        propeller = new VictorSP(6);
        addChild("Propeller",propeller);
        propeller.setInverted(false);
        
        servo1 = new Servo(1);
        addChild("Servo1",servo1);
        
        
        servo2 = new Servo(2);
        addChild("Servo2",servo2);
        
        
        servo3 = new Servo(3);
        addChild("Servo3",servo3);
        
        
        servo4 = new Servo(4);
        addChild("Servo4",servo4);
        
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new RawVacuum());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public boolean checkFanStatus(){
        //checks if the fan is on or off.
        return fanstatus;
        //true==on
    }
    public boolean checkSuckStatus(){
        return suckStatus;
    }
    public void suckRing(){
        //code pending, needs to suck in ring, blow out ball
        suckStatus=true;
        //start==open
        //end=closed
        servo1.setAngle(150);;
        servo2.setAngle(140);
        servo3.setAngle(5);
        servo4.setAngle(45);
    }
    public void suckBall(){
        //does the opposite of suckRing
        suckStatus=false;
        servo1.setAngle(15);
        servo2.setAngle(15);
        servo3.setAngle(180);
        servo4.setAngle(150);
    }
    public void turnIt(){
        //if the fan is on, turns it off. else, turns it on.
        if (checkFanStatus()){
            turnitOff();
        }
        else{
            //note:the motors are probably not like this
            propeller.setSpeed(0.75);
            fanstatus=true;
            /*if (checkSuckStatus()){
                suckRing();
            }
            else{
                suckBall();
            }*/
        }
    }
    public void turnitOff(){
        propeller.setSpeed(0);
        fanstatus=false;
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        SmartDashboard.putBoolean("fanstatus", fanstatus);
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

